sudo: false
cache:
    directories:
        - $HOME/.composer/cache
env:
    - COMPOSER_OPTIONS="--prefer-lowest"
    - SYMFONY_VERSION="2.7.*" COMPOSER_OPTIONS=""
    - SYMFONY_VERSION="2.8.*" COMPOSER_OPTIONS=""
    - COMPOSER_OPTIONS=""
language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_OPTIONS="--prefer-lowest"
  allow_failures:
    - php: nightly

before_install:
    - |
        if [ "$SYMFONY_VERSION" != "" ]
        then
        composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
        fi

install: composer update ${COMPOSER_OPTIONS}

script: SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/phpunit --coverage-text
